## This is an example config file for gitweb.py

#repo_list = /home/user/<REPO_NAME>, /home/user/<REPO_NAME>
#repo_list = /home/user/code/repos/medusa, /home/user/code/repos/gitweb
repo_list = /home/user/Desktop/test
svg_size = 30